# 동기 vs 비동기(sync vs async)

## 동기 Synchronous

- 한번에 하나의 함수만 실행 Only 1 Call Stack & Execution Context
- 즉, 하나의 함수가 실행되는 동안 blocking.
- Single Thread in Single Process
- Runtime → Execution Context → CallStack

## 비동기 Asynchronous

- 한번에 하나의 함수만 실행 Only 1 Call Stack & Execution Context
- 비동기 함수는 Backgound에 넘김 (Non-blocking)
- Single Thread But, Multi Process (:Background는 OS Process 의존)<br/>
  node가 multi process라는게 아님
- Runtime → Execution Context → CallStack → Background → OS → Task Queue → CallStack

## CallStack, TaskQueue, EventLoop, Background

- CallStack(호출 스택): 실행되는 함수가 등록되는 Stack.
- TaskQueue(태스크 큐): 실행되어야 할 콜백 함수가 대기하는 Queue.
- EventLoop(이벤트 루프): TaskQueue에 있는 함수를 차례로 CallStack으로!
- Background(백그라운드): 별도 Process로 I/O처리 후 콜백함수(in APIs Container)를 TaskQueue로!

### Browser Web APIs container

브라우저 접근 권한이 제한되어 있어서 이 세가지밖에 없음

- Event listeners
- Timing functions
- AJAX requests

cf. OS의 영역: sandbox

## JS Engine vs JS Runtime

engine < runtime

### JS Engine

- V8 - Google, chrome, (+) recent Edge(chromium base)
- Spider Monkey - Netscape, firefox
- WebKit - Apple Nitro, Safari
- Chakra - MS, ie, <s>edge(before chromium)</s>

### JS Runtime

- Browser - Chrome, Safari, Firefox, Brave, Edge, etc
- Node - Ryan Dhal, V8 Engine
- Deno - Ryan Dhal, V8 Engine, No npm, EJM only(CommonJS excluded), TS

## 전통적인 비동기

1. Callback: callback hell, error-first callback pattern

```js
setTimeout(function () {
  console.log("task1", new Date());
  setTimeout(function () {
    console.log("task2", new Date());
    setTimeout(function () {
      console.log("task3", new Date());
      console.log("END>>", new Date());
    }, 1000);
  }, 2000);
}, 3000);

console.log("START", new Date());
/// START -> task1 -> task2 -> task3
```

2. Promise: catch, catch, finalcatchCallback pattern의 단점을 극복하기 위해 출현

- 안전하고, 유지보수 쉬운 코드 작성 가능 exception safe! callback은 pop되었으니 catch 어떻게?!

```js
try {
  setTimeout(() => {
    console.log(new Date());
    throw new Error("어디로?");
  }, 1000);
} catch (err) {
  console.error("잡히나?", err);
}
// try -> catch -> setTimeout(()=>{}, 1000)
// setTimeout이 돌아올 때는 이미 try catch는 사라져있음
```

- Promise가 Callback을 대체하는 것은 아님! promise도 callback 사용!
- 호출 시 Promise instance 반환 후 resolve & reject 성공이나 실패하면 Promise settled!
  → Promise instance를 전달할 수 있어 편리함! const p = new Promise(resolveFn, rejectFn);
- Promise 객체는 성공(fulfiled) 또는 실패(rejected) 상태를 갖는다.
  (pending
  → fulfiled or rejected
  → settled)

```js
const promi = new Promise((resolve, reject) => {
  setTimeout(() => {
    const now = Date.now();
    if (now % 2 === 0) resolve(console.log("fulfill", now));
    else reject(new Error("어디로?"));
  }, 1000);
});

console.log(promi); // Promise { <pending> }

promi.then(
  (succ) => console.log("Resolve!"),
  (fail) => console.log("Reject!", fail)
);
```

### 결정되지 않은 프로미스 방지

```js
const promi = new Promise((resolve, reject) => {
  //   … 복잡한 로직…
  //   … 또는 문제 발생 시 오래걸림…
  setTimeout(() => {
    reject(new Error("Timeout!"));
    // 또는 resolve('skip!');
  }, 10000); // 10초이상 지나면 강제로 끊어버림
});
```

### 상태 (state)

- pending: 대기 중
- rejected: 실패했을 경우

### 메소드

- then: try, catch
- catch: only catch
- finally: error 여부와 상관없이 실행함. ex) db.end();

```js
promi
  .then((succ) => console.log("Resolve!", succ))
  .catch((err) => console.log("Error!!>>", err))
  .finally(() => console.log("finally"));
```

- resolve: 이미 존재하는 값
- reject: 에러

### promise chaining

```js
const promiseFn = (id = 1) =>
  new Promise((resolve, reject) => {
    console.log("id>>", id);
    if (id < 7) resolve(id + 1);
    else reject(new Error("어디로?" + id));
  });

promiseFn(1) // 1
  .then((res) => {
    console.log("res1>>", res); // 2
    promiseFn(res); // 2
  })
  .then((res) => {
    console.log("res2>>", res); // ?
    return promiseFn(res ?? 3); // ?
  })
  .then(promiseFn) // ?
  .then((res) => {
    console.log("res3>>", res); // ?
    return promiseFn(res); // ?
  })
  .then(promiseFn(4)) // 4
  .then((res) => promiseFn(res)) // ?
  .catch((err) => console.log("Error!!>>", err));
```

1. promiseFn(1)이 먼저 실행 -- 1
2. then(promiseFn(4)) 내부가 이미 실행되버림 -- 4<br/>  
   동기 쪽은 task queue에 안가기 때문에

```js
const promiseFn = (id) =>
  new Promise((resolve, reject) => {
    console.log("id>>", id);
    if (id < 5) resolve(id + 1);
    else reject(new Error("어디로?" + id));
  });

promiseFn(1)
  .then((res) => {
    console.log("res1>>", res);
    return promiseFn(res); // 2
  })
  .then((res) => {
    console.log("res2>>", res);
    return promiseFn(res); // 3
  })
  .then(promiseFn) // 4
  .then((res) => promiseFn(res)) // 5
  .catch((err) => console.log("Error!!>>", err));
```

## try this:

### 1. callback to promise

문제코드

```js
setTimeout(function () {
  console.log("depth1", new Date());
  setTimeout(function () {
    console.log("depth2", new Date());
    setTimeout(function () {
      console.log("depth3", new Date());
      throw new Error("Already 3-depth!!");
    }, 3000);
  }, 2000);
}, 1000);

console.log("START!", new Date());
```

my code

```js
const depthFn = (depth = 1) =>
  new Promise((res, rej) => {
    setTimeout(() => {
      console.log(`depth${depth}`, new Date());
      if (depth < 3) {
        res(depth + 1);
      } else rej(new Error("Already 3-depth"));
    }, depth * 1000);
  });

depthFn()
  .then(depthFn)
  .then(depthFn)
  .catch((err) => console.log(err));
```

### 임의의 시간에 resolve를 실행하는 함수를 생성

문제코드

```js
const randTime = (val) => {};

[1, 2, 3, 4, 5].forEach((a) => randTime(a).then(console.log));
```

my code

```js
const randTime = (val) =>
  new Promise((res, rej) => {
    const state = Math.random() * 1000;
    console.log("randTime>>", val, state);
    setTimeout(res, state, val);
  });
[1, 2, 3, 4, 5].forEach((a) => randTime(a).then(console.log));
```

### make promise

다음과 같이 실행되는 나만의 Promise 함수를 작성하시오.

<br/>문제코드

```js
const p = new Promise((resolve, reject) => {
  setTimeout(() => {
    const now = Date.now();
    if (now % 2 === 0) resolve(console.log("fulfill", now));
    else reject(new Error("어디로?"));
  }, 1000);
});

console.log("111>>", p);
setTimeout(() => console.log("222>>", p), 2000);
```

answer

```js
function Promise(cb) {
  Promise.prototype.then = (tcb) => {
    Promise.prototype.thenFn = tcb;
    return this;
  };
  Promise.prototype.catch = (ccb) => {
    Promise.prototype.catchFn = ccb;
    return this;
  };
  const resolve = (succ) => {
    console.log("RESOLVE!!", succ);
    this.state = "resolve";
    this.thenFn(succ);
  };
  const reject = (err) => {
    console.log("REJECT!!", err);
    this.state = "reject";
    if (this.catchFn) this.catchFn(err);
  };
  cb(resolve, reject);

  if (new.target) this.state = "pending";
}
```

### promise.all 구현하기

테스트 코드

```js
import { assertArray } from "../utils/test-utils.js";
const vals = [1, 2, 3];
const randTime = (val) =>
  new Promise((resolve) => setTimeout(resolve, Math.random() * 1000, val));

promiseAll([randTime(1), randTime(2), randTime(3)])
  .then((arr) => {
    console.table(arr);
    assertArray(arr, vals);
  })
  .catch(console.error);

promiseAll([randTime(11), Promise.reject("RRR"), randTime(33)])
  .then((array) => {
    console.log("여긴 과연 호출될까?!");
  })
  .catch((error) => {
    console.log("reject!!!!!!>>", error);
  });
```

answer

```js
// using Promise
const promiseAll = (promises) => {
  if (!promises?.length) return Promise.reject("empty arr");
  return new Promise((resolve, reject) => {
    const results = [];
    let pending = promise.length;
    for (let i = 0; i < promises.length; i += 1) {
      promises[i]
        .then((res) => {
          results[i] = res;
          pending -= 1;
          console.log("currentResults :>> ", results);
          if (!pending) resolve(results);
        })
        .catch(reject);
    }
  });
};

// using async await

const promiseAll2 = async (promises) => {
  const results = [];
  console.time("asyncTest");
  for (const promi of promises) {
    results.push(await promi); //prom.then()
  }
  console.timeEnd("asyncTest");
  return results;
};
```

3. <s>Generator: yield & next() <br>
   Async / Await: Only 1 Call Stack & Execution Context</s>
